'use client'
import { Inter } from "next/font/google";
import { useState } from "react";
import { ArrowRight, ChevronRight, DownloadCloud, House, Menu } from "lucide-react";
import SideBar from "./sideBar/SideBar";


const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [menuOpen,setMenuOpen]=useState(false)
  const [change,setChange]=useState(false)
  const [topHead,setTopHead]=useState(40)
  const menuHandle=()=>{
    setMenuOpen(!menuOpen)
  }

  
  const changeMenu=()=>{
    setTopHead(40-document.getElementById('content').scrollTop)
  //  console.log(document.getElementById('content').scrollTop,topHead)
    if (document.getElementById('content').scrollTop <30) {
      setChange(false)
    } else if(document.getElementById('content').scrollTop >=56){
      setChange(true)
    }
  }

  let route=document.location.href.split('/')
  route=route.slice(4,)
  return (
    <html lang="en">
      
      <body className={inter.className} >
      <div className="flex h-screen bg-gray-100">
    <div className='hidden lg:flex'><SideBar /></div>  
      <div className=' z-40 lg:z-auto absolute lg:hidden transition-[left] ease-in-out delay-100' style={menuOpen?{left:0}:{left:'-100%'}}>  <SideBar /> </div>
    <div className='rotate-180 flex absolute  top-6 z-50  lg:hidden transition-[left] ease-in-out delay-100' style={menuOpen?{left:'200px'}:{left:'-100%'}}> <ArrowRight onClick={menuHandle}/></div>
    
      <div className="flex flex-col overflow-auto w-[100%] " id="content" onScroll={changeMenu}>
        {/* Header */}
        <header className="bg-white p-4 shadow-sm  border-b-2 border-solid border-gray-200 h-[60px]" >
          <div className="flex items-center justify-between flex-row">
          <div class="flex flex-row items-center  overflow-x-auto whitespace-nowrap hidden lg:flex ">
        <div><House/></div>  
            {route.map((item,index)=>(
              <div className="flex flex-row gap-1 shadow-md shadow-gray-100">
            <ChevronRight/>
            <p>{item}</p>
           </div>
            ))}

            </div>
            
            <div class="flex  items-center  -mx-2 lg:hidden">
            
        <img class="object-cover w-10 h-10 mx-2 rounded-full" src="https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" alt="avatar" />
      {change==false?<div className=" w-6 h-6 bg-white absolute  left-[32px]  rounded-full shadow-md border-gray-100 border-solid border-2 " onClick={menuHandle} 
      style={{top:topHead}}>
        <Menu className='w-5 h-5'/></div>
      :<div className=" w-6 h-12 bg-[#ff8367] absolute top-[40px] left-[-4px] rounded-2xl shadow-md shadow-orange-500 border-solid border-2 pt-3 " onClick={menuHandle} >
        <ChevronRight color="#ffff" />
          </div>}
        <h4 class="mx-2 mt-2 font-medium text-gray-800 ">El-hathat mohamed</h4>
      </div>
            <div className="flex items-center space-x-4">
              
              <button className="p-2 rounded-full hover:bg-gray-100">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                </svg>
              </button>
              <button className="flex flex-col lg:flex-row items-center space-x-2 text-xs lg:text-lg">
                    <DownloadCloud />
                    <span>Emplois du temps</span>
              </button>
            </div>
          </div>
        </header>
        <div className="mt-1" >
          {children}
          </div>
        
        </div>
        </div>
        
        </body>
    </html>
  );
}
